# Generated by Django 4.2.5 on 2023-10-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('order_date', models.DateField(auto_now=True)),
                ('amount', models.FloatField()),
                ('item_id', models.CharField(max_length=100)),
            ],
        ),
    ]
